# Generated by Django 5.1.4 on 2025-01-22 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_otp_customuser_otp_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_created_at',
        ),
    ]
